language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      
install:
  - pip3 install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE=LocalizrExample.settings.default

script:
  - python manage.py test
